name       : perl-x11-protocol
version    : 0.56
release    : 8
source     :
    - http://search.cpan.org/CPAN/authors/id/S/SM/SMCCAM/X11-Protocol-0.56.tar.gz : de96dd6c7c1f25f3287aa7af64902bf84acaaa8e0c3bb76aa1676367e04a08b7
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Perl module for the X Window System Protocol, version 11
description: |
    Perl module for the X Window System Protocol, version 11
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
